### ISSUE TITLE
Is this possible run in Google Colab?

### ISSUE THREAD

**Issue by linpeisensh** [nileshkulkarni/csm#10]
Thank you for your excellent work!

I have tried to run experiment/csm/csp in Colab, but it shows this error:
![image](https://user-images.githubusercontent.com/52672986/80908676-1e00e100-8d22-11ea-83d8-84a6da816dfd.png)

Do you have any idea?

I look forward to your answer.

**Comment by nileshkulkarni** [comment]
I'm not sure exactly what is the issue. It appears that the issue is related to some GUI backend. 

Best,
Nilesh

**Comment by linpeisensh** [comment]
Thank you for your reply.

This problem happened, because I didn't move the cachedir into csm. It's my fault.

But now I can not get the resource of cachedir.
![image](https://user-images.githubusercontent.com/52672986/81147245-30755780-8f7a-11ea-8dbb-f25cc807ece5.png)

Since I use colab, I need to download it every time. Could you help me?

I look forward to your information.

Peisen Lin

**Comment by nileshkulkarni** [comment]
Hi,
I think there has been an issue with my box account. Please use the following link in the time being
https://umich.box.com/s/nncgnzht90s9dnahodel116hgykmmf6o

**Comment by linpeisensh** [comment]
Got it, thanks!
