### ISSUE TITLE
the details from UV map to 3d coordinate

### ISSUE THREAD

**Issue by asurada404** [nileshkulkarni/csm#12]
Thank you for your wonderful work!
I have two questions about the code.
Q1. In mean shape, Giving a point on the UV map, how to find its corresponding face(triangle)?
Q2. Asking for more references about the calculation of φ.
I have got that the calculation of φ(the process from UV map to 3d coordinate) was referred to [this paper]( http://hhoppe.com/proj/sphereparam/).
Could you please show me more references, such as links and formulations, about the calculation of φ.
For example, I know [these lines](https://github.com/nileshkulkarni/csm/blob/5c7d2d0cf12b4db11238cbdec4f718ae1217c639/csm/utils/cub_parse.py#L61-L85) are calculating the barycentric coordinates, but I want to know the formulations behind these codes.
Thanks a lot!!

**Comment by nileshkulkarni** [comment]
Hi, 
Here are the steps to create a mapping for the UV model. These instructions are also available [here](https://github.com/nileshkulkarni/csm/blob/master/csm/docs/preprocess.md)

Step 1 -- this is for Q2
We used the code from [here](https://www.numerical-tours.com/matlab/meshdeform_2_parameterization_sphere/) to create an alignment between the sphere and template level shape. The code has been repurposed [here](https://github.com/nileshkulkarni/csm/tree/master/csm/preprocess/parameterize/meshdeform). Please make sure you edit the paths in the startup.m file. Also, make sure the .off file corresponding to your template is present in the `meshdeform/toolbox_graph` directory.


Step 2 -- this code answers your Q1
Second, once that is done we need to create lookup table that maps UV values to face-ids. For that please run the code [here](https://github.com/nileshkulkarni/csm/blob/master/csm/preprocess/parameterize/uv_to_vertex_map.py). 

`python -m csm.preprocess.parameterize.uv_to_vertex_map <path/to/mat/file/from/matlab/script/shape.mat>  <path/to/output/mafile/shape.mat>
`
The shape.mat file for every category is correspondingly referred [here](https://github.com/nileshkulkarni/csm/blob/5c7d2d0cf12b4db11238cbdec4f718ae1217c639/csm/experiments/csm/csp.py#L118-L126)


I hope this helps. Let me know if you have more questions.

Best,
Nilesh

**Comment by nileshkulkarni** [comment]
In terms of pseudo-code for your first questions. the face_id  corresponding to the UV mapping. 

1. We sample a 1000x1000 grid uniformly for UV values that belong to [0,1].
2. For every UV

-  map the UV coordinate to the point on a 3D on a sphere (understand UV as latitude and longitude on a globe). 
- find the nearest face on the pre-defined  sphere template mesh which has 1280 faces and 642 vertices
-  Store that face_id corresponding to the UV

**Comment by asurada404** [comment]
Thanks a lot!
