### ISSUE TITLE
Failures while setting up environment from csm.yml

### ISSUE THREAD

**Issue by nishantrai18** [nileshkulkarni/csm#13]
Hey, first off thanks for the great work; it's great seeing progress towards less supervision even in 3D computer vision. 

I was setting up the repo in order to run some comparisons and faced some issues while creating the environment from `csm.yml`. I run into the following issue due to missing packages

```
> conda env create -f csm.yml
ResolvePackageNotFound:
  - bleach=1.5.0=py27_0
  - html5lib=0.9999999=py27_0
  - cudatoolkit=8.0=3
```

Upon further inspection, it seemed the packages were outdated. I changed the package versions to something still available in conda forge but even that didn't help. After a few more changes i.e. shifting a couple libraries under pip in csm.yml, I was blocked by multiple conflicts.

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package wheel conflicts for:
pip==18.1=py27_0 -> wheel
Package sqlite conflicts for:
qt==5.6.3=h8bf5577_3 -> sqlite[version='>=3.25.3,<4.0a0']
python==2.7.15=h9bab390_4 -> sqlite[version='>=3.25.2,<4.0a0']
Package six conflicts for:
tensorflow-gpu-base==1.4.1=py27h01caf0a_0 -> six[version='>=1.10.0']
mock==2.0.0=py27_0 -> six
protobuf==3.6.1=py27he6710b0_0 -> six
```

Would you have any suggestions for the above? Should I create my own environment and install the necessary packages by myself? Would really appreciate your help with this, cheers!

**Comment by nileshkulkarni** [comment]
Hi @nishantrai18,
Thanks for trying this out! Please go ahead and please create a new env. Here a few packages you might need.

python=2.7
cuda=8.0
pytorch=0.4
pymesh (follow instructions [here](https://pymesh.readthedocs.io/en/latest/))

NMR only works with python=2.7 (also please make sure NMR is working by running the test inside it).
Alternately, you can refer to [this](https://github.com/akanazawa/cmr/blob/master/requirements.txt) requirements file 

Best, 
Nilesh

**Comment by nishantrai18** [comment]
Thanks for the pointers! FYI for anyone bumping into this: I managed to get it working with a combination of what Nilesh suggested and building things from scratch.
