### ISSUE TITLE
Access to Images from ImageNet dataset

### ISSUE THREAD

**Issue by harinandan1995** [nileshkulkarni/csm#15]
Hello,
I would like to know if I could get access to the images from ImageNet used in your project or at least the mapping of image URLs and names used in the annotation files.

**Comment by nileshkulkarni** [comment]
Hi,
The image names from ImageNet are available from the mat file that is read on these lines.
https://github.com/nileshkulkarni/csm/blob/848fa12039551de6c7ba796685f568a8bba65ab2/csm/data/imagenet.py#L63-L64

Please look at the annotations inside this mat file. Let me know if there was anything else. 

Best,
Nilesh

**Comment by harinandan1995** [comment]
Thanks for the reply. I later found that the ImageNet provides an API for the URL to ID mapping.
