### ISSUE TITLE
Doubut about PCK Metrics in this paper

### ISSUE THREAD

**Issue by linpeisensh** [nileshkulkarni/csm#18]
Hello!

I have doubt about your PCK metrics. 
In your paper you write:
![image](https://user-images.githubusercontent.com/52672986/88214871-200c7900-cc5b-11ea-8629-09ff65bee35a.png)
Is h and w here the original height and width of images or cropped size (256)?
Thank you!

**Comment by nileshkulkarni** [comment]
It's the cropped size.

**Comment by linpeisensh** [comment]
Since we crop this image to 256*256, why we still need to use max? It confused me.

Thank you for your answer!

**Comment by shubhtuls** [comment]
You are right that in our specific case, h=w. The general definition of PCK though does have a max, hence equation in the paper.
