### ISSUE TITLE
Quaternion Azimuth-Elevation predictor

### ISSUE THREAD

**Issue by tejank10** [nileshkulkarni/csm#20]
Hello Nilesh,

In the quaternion azimuth-elevation predictor, linear layer output is never used. Is that intended? On [this](https://github.com/nileshkulkarni/csm/blob/13e675905b7acdca0a11a0db1be281d17da6394a/csm/nnutils/icn_net.py#L145) line.

Thanks.

**Comment by nileshkulkarni** [comment]
Hi @tejank10, 
Thanks for pointing that out, you could have the model work both ways. You could have a linear layer or not.  It probably helps (at least won't harm to have the linear layer). It was not intended to be like this, but all our models are trained without using it.  There are multiple linear layers [here](https://github.com/nileshkulkarni/csm/blob/13e675905b7acdca0a11a0db1be281d17da6394a/csm/nnutils/icn_net.py#L210) so it would be equivalent to adding another linear layer.

Best,
Nilesh
