### ISSUE TITLE
Pre-trained weights?

### ISSUE THREAD

**Issue by sunshineatnoon** [nileshkulkarni/csm#3]
Hi, thanks for open-sourcing this wonderful work. Could you also provide weights of pretrained CSM model? Thanks!

**Comment by nileshkulkarni** [comment]
Hi!
I have added it in the cachedir. Please download it again. Hope this helps!
Thanks!

**Comment by sunshineatnoon** [comment]
Found the weights. Thanks! You might want to update the link here too:

`Download our [annotation files](https://cmu.box.com/s/e8y71bjuwxrdrypy44zu3z8qexmnyqp4) and pre-computed UV parameterization outputs. Do this from the csm_root/csm/ directory, and this should make csm_root/csm/cachedir directory. This also contains weights from the pretrained models.`
