### ISSUE TITLE
csm/csm/docs/testing.md error

### ISSUE THREAD

**Issue by felixboevr** [nileshkulkarni/csm#7]
Hi, I get this error for running the "Eval keypoint transfer" commands. 
>   File "csm/utils/render_utils.py", line 1, in <module>
    import pymesh
ImportError: No module named pymesh

I tried to install Pymesh but it only supports Python 3.7 - in your requirements it says Python 2.7 though. What do you suggest?

**Comment by felixboevr** [comment]
Installing pymesh did not work with "conda install pymesh". 
It did work with "Conda install pip" and then "pip install pymesh" though

**Comment by nileshkulkarni** [comment]
So pymesh is not available to install via pip, I suggest you to 
 use this https://pymesh.readthedocs.io/en/latest/installation.html to install it from source!

**Comment by felixboevr** [comment]
this was most helpful to get PyMesh working with Python 2.7. https://github.com/PyMesh/PyMesh/issues/110#issuecomment-422138489

**Comment by felixboevr** [comment]
So Pymesh works but I get another error now when trying your test in https://github.com/nileshkulkarni/csm/blob/master/csm/docs/testing.md

> RuntimeError: Error(s) in loading state_dict for ICPNet: Unexpected key(s) in state_dict: "img_encoder.resnet_conv.resnet.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer1.0.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer1.0.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer1.1.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer1.1.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer2.0.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer2.0.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer2.0.downsample.1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer2.1.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer2.1.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer3.0.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer3.0.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer3.0.downsample.1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer3.1.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer3.1.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer4.0.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer4.0.bn2.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer4.0.downsample.1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer4.1.bn1.num_batches_tracked", "img_encoder.resnet_conv.resnet.layer4.1.bn2.num_batches_tracked", "img_encoder.enc_conv1.1.num_batches_tracked"

Any suggestions? Thank you

**Comment by felixboevr** [comment]
also managed that with the help of this post https://discuss.pytorch.org/t/missing-keys-unexpected-keys-in-state-dict-when-loading-self-trained-model/22379/6
