### ISSUE TITLE
csm/docs/testing.md IOError

### ISSUE THREAD

**Issue by felixboevr** [nileshkulkarni/csm#8]
Eval keypoint transfer on birds throws error:

> IOError: [Errno 2] No such file or directory: '/nfs.yoda/nileshk/CorrespNet/datasets/cubs/images/083.White_breasted_Kingfisher/White_Breasted_Kingfisher_0115_73252.jpg'

Eval keypoint transfer on cars  throws error:

> IOError: [Errno 2] No such file or directory: '/nfs.yoda/nileshk/CorrespNet/datasets/PASCAL3D+_release1.1/Images/car_imagenet/n04037443_13265.JPEG'

**Comment by nileshkulkarni** [comment]
Hi,
Please download the datasets and please change the path to the respective paths. You would need a downloaded copy of the [cubs](https://github.com/nileshkulkarni/csm/blob/master/csm/docs/training.md) and the [car](https://github.com/nileshkulkarni/csm/blob/master/csm/preprocess/pascal/pascal.md) dataset from PASCAL3D+ dataset.

Thanks,
Nilesh
